[package]
name = "crush-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "crushctl"
path = "src/main.rs"

[dependencies]
crush-core = { path = "../core" }
crush-stage-split = { path = "../stage-split" }
crush-stage-embed = { path = "../stage-embed" }
crush-search = { path = "../search" }
crush-store = { path = "../store" }
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
image.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
tempfile = "=3.27.0"
